[package]
name = "opengl101"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
gl = "0.14.0"
glfw = "0.60.0"
image = "0.25.8"
winit = "0.30.12"
glutin = "*"
glutin-winit = "*"
raw-window-handle = "0.6.2"
